version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  web:
    build:
      dockerfile: dockerfile-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ".:${CWD:-/code}"
    depends_on:
      - postgres

volumes:
  postgres-db: